BLOCKED_SITES = [
    "facebook.com",
    "www.youtube.com",
    "https://www.youtube.com/",
    "https://www.youtube.com",
    "youtube.com",
    "www.instagram.com",
    "instagram.com",
    "www.twitter.com",
    "twitter.com",
    "reddit.com",
    "www.tiktok.com",
    "tiktok.com",
    "www.twitch.tv",
    "twitch.tv",
    # Reddit variants
    "www.reddit.com",
    "old.reddit.com",
    "new.reddit.com",
    "np.reddit.com",
    # Add https and http explicitly
    "https://reddit.com",
    "https://www.reddit.com",
    "http://reddit.com",
    "http://www.reddit.com",
    '/r/',
    # Add your other sites with similar variants
    "facebook.com",
    "www.facebook.com",
    "4chan.org",
    "www.4chan.org",
    "4chan.net",
    "www.4chan.net",
    "4channel.org",
    "www.4channel.org",
    "sflix.to",
    "www.sflix.to",
    "netflix.com",
    "www.netflix.com",
    "netflix.net",
    "www.netflix.net",
]